import { assertType, it } from "vitest";
import type { ImportHTMLBookmarkFileResponse } from "~/generated/api";

it("importHTMLBookmarkFile", () => {
	assertType<ImportHTMLBookmarkFileResponse>({
		result: true,
		items: [
			{
				title: "Bookmarks bar",
				folders: [
					{
						title: "Keyboard Shortcuts",
						folders: [],
						bookmarks: [
							{
								link: "https://support.google.com/chrome/answer/157179?co=GENIE.Platform=Desktop&hl=en",
								title: "Chrome keyboard shortcuts",
								excerpt: "",
								created: "2023-03-09T01:22:45.000Z",
								lastUpdate: "2023-03-09T01:22:45.000Z",
								tags: [],
								note: "",
								cover: "",
								media: [],
								important: false,
							},
						],
					},
				],
				bookmarks: [
					{
						link: "https://containers.dev/features",
						title: "Dev Container Features",
						excerpt: "",
						created: "2024-03-24T13:58:25.000Z",
						lastUpdate: "2024-03-24T13:58:25.000Z",
						tags: [],
						note: "",
						cover: "",
						media: [],
						important: false,
					},
					{
						link: "https://devv.ai/en",
						title: "Devv",
						excerpt: "",
						created: "2024-02-17T01:33:16.000Z",
						lastUpdate: "2024-02-17T01:33:16.000Z",
						tags: [],
						note: "",
						cover: "",
						media: [],
						important: false,
					},
					{
						link: "https://gemini.google.com",
						title: "Gemini",
						excerpt: "",
						created: "2023-04-22T02:40:55.000Z",
						lastUpdate: "2023-04-22T02:40:55.000Z",
						tags: [],
						note: "",
						cover: "",
						media: [],
						important: false,
					},
					{
						link: "https://chat.openai.com/chat",
						title: "ChatGPT",
						excerpt: "",
						created: "2023-01-29T13:03:03.000Z",
						lastUpdate: "2023-01-29T13:03:03.000Z",
						tags: [],
						note: "",
						cover: "",
						media: [],
						important: false,
					},
				],
			},
			{
				title: "Import",
				folders: [],
				bookmarks: [
					{
						link: "https://hub.docker.com",
						title: "Docker Hub",
						excerpt: "",
						created: "2024-04-04T14:20:27.000Z",
						lastUpdate: "2024-04-04T14:20:27.000Z",
						tags: [],
						note: "",
						cover: "",
						media: [],
						important: false,
					},
					{
						link: "https://www.reddit.com",
						title: "Reddit",
						excerpt: "",
						created: "2023-05-12T09:24:43.000Z",
						lastUpdate: "2023-05-12T09:24:43.000Z",
						tags: [],
						note: "",
						cover: "",
						media: [],
						important: false,
					},
					{
						link: "https://stackoverflow.com",
						title: "Stack Overflow",
						excerpt: "",
						created: "2023-05-12T09:24:37.000Z",
						lastUpdate: "2023-05-12T09:24:37.000Z",
						tags: [],
						note: "",
						cover: "",
						media: [],
						important: false,
					},
				],
			},
		],
		count: { bookmarks: 8, folders: 3, tags: 0, highlights: 0, duplicates: 0 },
	});
});
